### ISSUE TITLE
Deleting the Product

### ISSUE THREAD

**Issue by CodeByVishaal** [akshayrock45/Smart-Inventory-Backend#10]
When trying to delete a product with Stock as False , its not deleting. Need to change the isStock() logic , just fetch by Id and Delete.
![image](https://github.com/akshayrock45/Smart-Inventory-Backend/assets/68778483/beb439f5-9fa2-4f43-a3b7-eef9166aec3b)

**Comment by subhams56** [comment]
Stock column removed issue solved.
